on: push
name: CI
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install
        run: npm install
      - name: Tests
        run: npm test
    env:
      CI: true
    strategy:
      fail-fast: true
